# Generated by Django 3.2.6 on 2021-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
