# Generated by Django 3.2.6 on 2021-08-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='friendly_brand',
            field=models.CharField(default='i', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(default='e', max_length=254),
            preserve_default=False,
        ),
    ]
